### ISSUE TITLE
old bird animation problem

### ISSUE THREAD

**Issue by swagseija** [BoredBean/TouhouCompany#8] opened 2024-05-18 09:10 UTC
hello!

there seems to be animation problems regarding old bird in the latest version of this mod.
when i have this mod enabled, old birds dont walk or do play any other animation after spotting a player.
they do move and shoot, just without any animation.
the problem still persists even if i disabled the oku skin and enabled the other skins, 
i had to disable the mod for old birds to behave normally.

hope there will be a fix soon, i really like your mod! (especially the sekibanki coilhead)

**Comment by BoredBean** [comment] 2024-05-18 23:56
Thank you swagseija,

It's a stupid bug, but it will be fixed soon.

**Comment by BoredBean** [comment] 2024-05-19 04:33
### Release v0.9.7
1. Fixed Old-Bird animations.
2. Fixed Utsuho animations.
* ℹ️Old-Bird **stops moving** if its **target(including giants)** is eaten by a **Sandworm** while attacking. **Not caused by this mod.**
* ℹ️Old-Bird **stops moving** if a player is **grabbed** by Old-Bird but **not killed** by its flame. This **can be fixed** with a single **touch** to the Old-Bird from a player. **Not caused by this mod.**
* ℹ️The missiles launched by **Utsuho** had 30%-50% of the **hit rate** of Old-Birds. This can be fixed, but it **makes sense** considering that Utsuho is not very smart. It also makes life easier.

Now Utsuho behaves exactly like the old bird, only slightly less intelligent.

**Closed as completed by BoredBean** 2024-05-19 04:33 UTC
